/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

// Clean old caches
cleanupOutdatedCaches()

// Precache resources generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

// Claim clients so the SW takes control immediately
self.skipWaiting()
clientsClaim()

// Push event listener for Web Push Notifications
self.addEventListener('push', (event) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    
    const options: any = {
      body: data.body || 'Ada update baru dari Ting AI',
      icon: '/pwa-192x192.png',
      badge: '/favicon.ico',
      vibrate: [100, 50, 100],
      data: {
        url: data.url || '/komando-pagi'
      }
    }

    event.waitUntil(
      self.registration.showNotification(data.title || 'Ting AI Alert', options)
    )
  } catch (err) {
    // Fallback if data is just text
    event.waitUntil(
      self.registration.showNotification('Ting AI Alert', {
        body: event.data.text(),
        icon: '/pwa-192x192.png'
      })
    )
  }
})

// Notification click listener
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const targetUrl = event.notification.data?.url || '/komando-pagi'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(targetUrl)
          return client.focus()
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl)
      }
    })
  )
})
